# Site settings
title: tinychime ðŸ””
version: "v1"
tagline: "Design & Code"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
email: hireus@tinychime.com

# Tachyons Version
tv: "4.4.2"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]
